[package]
name = "rocs"
version = "1.0.10"
authors = ["OpenAPI Generator team and contributors"]
description = "Rust OSB client"
license = "MIT"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
clap = "2.33.0"
prettytable-rs = "^0.8"
uuid = { version = "0.8.1", features = ["v4"] }
spinners = "1.2.0"
time = "0.1.38"
dirs = "2.0.2"
rusqlite = "0.21.0"
rocl = "0.0.4"
valico = "3.2.0"

[dev-dependencies]
